### ISSUE TITLE
Example seems to not work

### ISSUE THREAD

**Issue by ImVexed** [briannoyama/bvh#1]
The example in the readme

```go
import "github.com/briannoyama/bvh/rect"

// Change the DIMENSIONS constant in orthotope.go for your use case.
orth := &rect.Orthotope{Point: [2]int{10, -20}, Delta: [2]int{30, 30}}
bvol := &rect.BVol{}
bvol.Add(orth)
bvol.Remove(orth)

// Use an iterator to reduce the amount of Garbage Collection
iter := bvol.Iterator()
iter.Add(orth)

q := &rect.Orthotope{Point: [2]int{10, -10}, Delta: [2]int{20, 20}}
for r := iter.Query(q); r != nil; r = iter.Query(q) {
    // Do something with each orthotope r
}

iter.Remove(orth)
```

Not only doesn't compile (`[3]int32`, not `[2]int`), but the `iter.Query` returns nil each time. Not sure if I'm missing something, but those orthotopes should intersect.

**Comment by briannoyama** [comment]
You're correct that the Orthotopes should intersect if there was anything in bvol! However, the line "bvol.Remove(orth)" takes the orth out of bvol, so it's basically testing an empty tree. This is definitely not obvious, and I should make a clearer example for how to use. Will push out a better example and update documentation.
